### ISSUE TITLE
Share submit causes pool worker fork to die

### ISSUE THREAD

**Issue by bobfeldbauer** [nginnever/unified-node-open-mining-portal#1]
Tested using nodejs v0.10.29

When shares are submitted, the pool worker fork that the miner is on dies:

/opt/zcash-nomp/node_modules/stratum-pool/node_modules/bignum/index.js:312
  if (buf.length % size !== 0) {
         ^
TypeError: Cannot read property 'length' of undefined
    at Function.BigNum.fromBuffer (/opt/zcash-nomp/node_modules/stratum-pool/node_modules/bignum/index.js:312:10)
    at JobManager.processShare (/opt/zcash-nomp/node_modules/stratum-pool/lib/jobManager.js:230:35)
    at null.<anonymous> (/opt/zcash-nomp/node_modules/stratum-pool/lib/pool.js:497:46)
    at emit (events.js:98:17)
    at handleSubmit (/opt/zcash-nomp/node_modules/stratum-pool/lib/stratum.js:167:15)
    at handleMessage (/opt/zcash-nomp/node_modules/stratum-pool/lib/stratum.js:72:17)
    at /opt/zcash-nomp/node_modules/stratum-pool/lib/stratum.js:240:25
    at Array.forEach (native)
    at Socket.<anonymous> (/opt/zcash-nomp/node_modules/stratum-pool/lib/stratum.js:226:26)
    at Socket.emit (events.js:95:17)
[2016-11-18 05:05:16.658] [ERROR] [default] - Master PoolSpawner Fork 3 died, spawning replacement worker...

**Comment by zhoujianwei** [comment]
same issue

[2016-11-27 18:29:04.362] [DEBUG] [default] - Payments zcash Finished interval - time spent: 60335ms total, 2ms redis, 331ms daemon RPC

/root/unomp/node_modules/stratum-pool/node_modules/bignum/index.js:312
  if (buf.length % size !== 0) {
         ^
TypeError: Cannot read property 'length' of undefined
    at Function.BigNum.fromBuffer (/root/unomp/node_modules/stratum-pool/node_modules/bignum/index.js:312:10)
    at JobManager.processShare (/root/unomp/node_modules/stratum-pool/lib/jobManager.js:233:35)
    at null.<anonymous> (/root/unomp/node_modules/stratum-pool/lib/pool.js:497:46)
    at EventEmitter.emit (events.js:98:17)
    at handleSubmit (/root/unomp/node_modules/stratum-pool/lib/stratum.js:167:15)
    at handleMessage (/root/unomp/node_modules/stratum-pool/lib/stratum.js:72:17)
    at /root/unomp/node_modules/stratum-pool/lib/stratum.js:240:25
    at Array.forEach (native)
    at Socket.<anonymous> (/root/unomp/node_modules/stratum-pool/lib/stratum.js:226:26)
    at Socket.EventEmitter.emit (events.js:95:17)
[2016-11-27 18:29:19.199] [ERROR] [default] - Master PoolSpawner Fork 1 died, spawning replacement worker...
